"""Create table sessions

Revision ID: 07682647a3ee
Revises: d3ca06a4f86e
Create Date: 2026-02-13 20:16:46.326122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07682647a3ee'
down_revision: Union[str, Sequence[str], None] = 'd3ca06a4f86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_uid'), ['session_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_uid'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_created_at'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
