"""Change name of table

Revision ID: d3ca06a4f86e
Revises: 961b97bdcc69
Create Date: 2026-02-13 20:06:02.152224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ca06a4f86e'
down_revision: Union[str, Sequence[str], None] = '961b97bdcc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uid', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('window_title', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('entry', sa.Text(), nullable=True),
    sa.Column('is_consulted', sa.Boolean(), nullable=True),
    sa.Column('is_written', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_consulted'), ['is_consulted'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_written'), ['is_written'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_session_uid'), ['session_uid'], unique=False)

    with op.batch_alter_table('event_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_raw_app_name'))
        batch_op.drop_index(batch_op.f('ix_event_raw_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_raw_duration'))
        batch_op.drop_index(batch_op.f('ix_event_raw_id'))
        batch_op.drop_index(batch_op.f('ix_event_raw_is_consulted'))
        batch_op.drop_index(batch_op.f('ix_event_raw_is_written'))
        batch_op.drop_index(batch_op.f('ix_event_raw_session_uid'))

    op.drop_table('event_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_raw',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_uid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('app_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('window_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('entry', sa.TEXT(), nullable=True),
    sa.Column('is_consulted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_written', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_raw_session_uid'), ['session_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_is_written'), ['is_written'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_is_consulted'), ['is_consulted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_raw_app_name'), ['app_name'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_session_uid'))
        batch_op.drop_index(batch_op.f('ix_events_is_written'))
        batch_op.drop_index(batch_op.f('ix_events_is_consulted'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_duration'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_app_name'))

    op.drop_table('events')
    # ### end Alembic commands ###
